name: video_stream_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  marquee: ^2.2.3
  msh_checkbox: ^2.0.1
  graphql_flutter: ^5.1.0
  provider: ^6.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/custom.otf

  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true 
